# Rutas de archivos CSV
data.path=data/
data.persons.name=persons.csv
data.products.name=products.csv
data.accounting.name=accounting.csv

# Validaciones de Persona
person.name.min=2
person.name.max=30
person.lastname.min=2
person.lastname.max=30

# Validaciones de Producto
product.description.min=3
product.description.max=50
product.price.max=999999.99

# Validaciones de Contabilidad
accounting.description.min=3
accounting.description.max=100

# Idioma (es | en | fr)
app.language=es